config/routes.rb
Rails.application.routes.draw do
  get '/auth/facebook/callback' , to: 'users/sessions#create_user'

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    get 'homes/index'
  end
  #devise_for :users
     devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        omniauth_callbacks: "users/omniauth_callbacks" 
        #registrations: 'users/registrations'
      }


  namespace :web do
    resources :categories do
    collection do
      get :review_system
    end
    end

    resources :reviews do
      collection do
        get :review_chart, to: 'reviews#review_chart', as: 'review_chart'
        post :average_criteria
        post :average_bar_graph_data
        post :get_reviews
        post :get_vote_for_review
      end
    end
    get '/:name' , to: 'users#index' , as: 'users'
    resources :users, except: [:index] do
    collection do
      get :read_full_review
      get :check_email
      get :check_email_login
      post :image_update
      get :report
      get :report_details
      get :header_search
      get :user_score
      get :rating_product
      get :hollframe
      get :user_type
      get :trending
      get :upcomeing
      get :holl_of_fame_details
      get :categorywise
      get :rating_calculate
    end
    member do
      get :blockchain_data
      get :user_profile
      get :movie_category
      get :movie_category_detail
      get :movie_detail
      get :movie_review
      get :full_review
    end
   end 
  end

  namespace :admin do
    resources :users do
      collection do
        post :import
        get :change_admin_password
        # get :feedback
      end
    member do
        get :status
        get :admin_profile
        get :edit_admin_profile
        patch :update_admin_profile
        patch :type_user
        patch :expert_user
        # get :show_feedback
        # delete :destroy_feedback
      end
    end
    resources :faqs
    resources :feedbacks
    resources :static_content
    resources :categories do
      collection do
        get :edit_sub_category
        get :edit_review_part
       delete :destroy_sub_category
       delete :destroy_review_part
        post :create_sub_category
        post :create_post_review
        post :update_sub_category
        post :update_review_part
        get :add_category
        post :create_category_details
        get :search_sub_categories
      end
    end
    resources :products do
      collection do
        get :sub_categories_by_category
      end
      member do 
        patch :publish
        patch :show_in_banner
        get :add_links
        get :new_addlinks
        post :create_product_link
        delete :product_link_delete
        patch :unpublish
        patch :trending
      end
    end
      get 'homes/index', as: "home_index"
  end
   resources :homes do
      collection do
        get :about_us
        get :faq
        get :privacy_policy
        get :term_condition
        get :feedback
        get :contact_us
      end
    end
    root :to =>  "web/users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :users do
        collection do
            post :sign_up
            
        end 
      end
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :sub_categories,autosave: true, dependent: :destroy
	has_many :product, dependent: :destroy
	has_many :review_parts, dependent: :destroy
	# accepts_nested_attributes_for :sub_categories, allow_destroy: true
validates :category_name, length: { minimum: 2, maximum: 30}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
 before_action :authenticate_user!
 before_action :find_category, only: [:show,:edit,:update,:status,:destroy]
 layout 'admin_lte_2'

 def index
    @s_no = 0
    if params[:search].present?
       @categories = Category.where(category_name: params[:search])
       @categories = @categories.order("created_at desc").paginate(:page => params[:page], :per_page => 100)
    else
        @categories = Category.all
        @categories = @categories.order("created_at desc").paginate(:page => params[:page], :per_page => 8)
    end
  end

  
  
  def destroy
   @category = Category.find(params[:id])
   @category.destroy
   redirect_to admin_categories_path, notice: "Category  deleted successfully"
  end



	def new
	end

	def create
       category = Category.where(category_name: params[:category][:category_name])
       if category.present?
        flash[:notice] = "Category already exists"
        redirect_to admin_categories_path
       else
        @category = Category.create(category_params)
        if @category.save
          contract_instance.transact_and_wait.add_category(@category.category_name,@category.id) rescue nil
           redirect_to admin_categories_path, notice: 'Category Created Successfully.'
        else
           flash[:alert] = @category.errors.full_messages
           render :new
           flash[:notice] = "Category is not Create"
        end
      end
  end   

  def edit
   
    @s_no = 0

     if params[:search].present?
       @search = @category.sub_categories.where(sub_category_name: params[:search]).order("created_at desc").paginate(:page => params[:page], :per_page => 100)
       @search1 = @category.review_parts.where(criteria: params[:search]).order("created_at desc").paginate(:page => params[:page], :per_page => 100)
     else
        @search = @category.sub_categories.order("created_at desc").paginate(:page => params[:page], :per_page => 12)
        @search1 = @category.review_parts.order("created_at desc").paginate(:page => params[:page], :per_page => 12)
        
      
    end
    @sub_category = @search 
    @review_parts1 = @search1

  end

 

  

  def update
    if Product.where(category_id: params[:id]).present?
    Product.where(category_id: params[:id]).update(category_name: params[:category][:category_name])
  end
    if @category.update_attributes(category_params)
       redirect_to admin_categories_path, notice: 'Category updated Successfully.'
    else
       flash[:alert] = @category.errors.full_messages
       render 'edit'
       flash[:notice] = "Category is not update."
    end
  end

  def create_post_review
    
     @review_parts = ReviewPart.where(criteria: params[:review_parts][:criteria], category_id: params[:review_parts][:category_id])
     if @review_parts.present?
        flash[:notice] = "Review part criteria already exists"
      else
     @category=Category.find(params[:review_parts][:category_id])
    if a = @category.review_parts.create(review_part_params)
      contract_instance.transact_and_wait.add_criteria(params[:review_parts][:category_id],params[:review_parts][:criteria],a.id)
      flash[:notice] = "Review Parts create successfullly"
   else
      flash[:alert] = @category.errors.full_messages
      flash[:notice] = "Unable to create review parts"
    end
  end
  redirect_to edit_admin_category_path( params[:review_parts][:category_id])
  end

  def update_review_part
   
    review_part = ReviewPart.where(criteria: params[:review_parts][:criteria], category_id: params[:review_parts][:category_id])
    @category = Category.find_by(id: params[:review_parts][:category_id])
    @review_parts = ReviewPart.find_by(id: params[:criteria_id])
    if review_part.present?
      flash[:notice] = "criteria name is already exists"
    else
      if @review_parts.update(review_part_params)
         flash[:notice] = "criteria update successfullly"
      else
       flash[:alert] = @review_parts.errors.full_messages 
       flash[:notice] = "criteria is not update"
     end
    end
    redirect_to edit_admin_category_path( params[:review_parts][:category_id])
  end

  def destroy_review_part
    
  @review_parts =  ReviewPart.find_by(id: params[:id])
  @review_parts&.destroy
  redirect_to admin_categories_path, notice: "Criteria deleted successfully"
  end
 
 def edit_review_part
 
  @review_parts = ReviewPart.find_by(id: params[:id])
 end
  def create_sub_category
    sub_category = SubCategory.where(sub_category_name: params[:sub_categories][:sub_category_name], category_id: params[:sub_categories][:category_id])
    @category = Category.find( params[:sub_categories][:category_id])
    if sub_category&.present?
      flash[:notice] = "sub category already exists."
    else
      if @category.sub_categories.create(sub_category_params)
        flash[:notice] = "sub category created successfullly."
     else
        flash[:alert] = @category.errors.full_messages
        flash[:notice] = "Unable to create sub category."
      end
    end
     redirect_to edit_admin_category_path(params[:sub_categories][:category_id])
  end


  def edit_sub_category
     
     @sub_categories = SubCategory.find_by(id: params[:id])

  end


  def update_sub_category
   
    sub_category = SubCategory.where(sub_category_name: params[:sub_categories][:sub_category_name], category_id: params[:sub_categories][:category_id])
    @category = Category.find( params[:sub_categories][:category_id])
     @sub = SubCategory.find_by(id: params[:subcat_id])
     if sub_category.present?
      flash[:notice] = "sub category already exists."
    else
      if Product.where(sub_category_id: params[:subcat_id]).present?
        Product.find_by(sub_category_id: params[:subcat_id]).update(sub_category_name: params[:sub_categories][:sub_category_name])  
     end
    if @sub.update(sub_category_params)
       flash[:notice] = "sub category update successfullly."
      else
        flash[:alert] = @sub.errors.full_messages
        flash[:notice] = "sub category is not update"
      end
    end
    redirect_to edit_admin_category_path(params[:sub_categories][:category_id])
end
  
  def destroy_sub_category
   
   @sub_category = SubCategory.find(params[:id])
    @sub_category.destroy
   redirect_to admin_categories_path, notice: "Sub Category  deleted successfully"
  end


  private

  def category_params
    params.require(:category).permit(:category_name)
  end

  def find_category
    @category = Category.find_by(id: params[:id])
	  redirect_to admin_categories_path unless @category
  end

  def sub_category_params
   params.require(:sub_categories).permit(:sub_category_name, :category_id)
  end

  def review_part_params
    params.require(:review_parts).permit(:criteria, :category_id)
  end
  
end

app/controllers/web/categories_controller.rb
class Web::CategoriesController < ApplicationController
	def index
	end
	def review_system
	end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
	def category
		
		Category.all.pluck("category_name")
	end

	def sub_category
	SubCategory.all.pluck("sub_category_type")
	end
end

app/helpers/web/categories_helper.rb
module Web::CategoriesHelper
end

app/views/admin/categories/_edit_review_part.html.erb
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
       
        </div>
        <div class="modal-body">
          <div class="addbody text-left">
           <%= form_for :review_parts, url:  update_review_part_admin_categories_path, html: {id: "edit_review"}  do |f| %>


                 <div class="form-group">
                <label for="">Criteria Name<span class="required">*</span> </label>
                  <%= f.text_field :criteria,  class: "form-control custom-control",  placeholder: "Criteria Name"%>
                 </div>
               <%#= f.hidden_field :id, :value => '@sub.id'  %>
         <%= f.hidden_field :category_id, :value =>  @review_parts.category_id %>
              <input type = "hidden" name = "criteria_id" value = "<%=@review_parts.id%>">
               
       
        <div class="modal-footer text-center">
          <%= submit_tag 'Update', :class => "btn btn-primary btn-md"%>
        </div>
         </div>
        <%end%>
         </div>
      </div>

      
       <script type="text/javascript">
       $(document).ready(function(){

       $("#edit_review").validate({
     rules: {
       "review_parts[criteria]": {
         required: true,
         maxlength: 30,
         minlength: 2,
         lettersonly: true

       },
     },
     messages: {
       "review_parts[criteria]":{
         required: "Please enter the review name.",
         maxlength: "Maximum  characters are 30.",
         minlength: "Minimum characters are 2",
       },
     },
    });

jQuery.validator.addMethod("lettersonly", function(value, element) {
 return this.optional(element) || /^[a-z ]+$/i.test(value);
}, "Letters only please"); 
  });
     </script>

app/views/admin/categories/_edit_sub_cat.html.erb
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>

</div>
<div class="modal-body">
<div class="addbody text-left">
<%= form_for :sub_categories, url:  update_sub_category_admin_categories_path, html: {id: "edit_sub_categories"}  do |f| %>
<div class="form-group">
<label for="">Sub Category Name<span class="required">*</span> </label>
<%= f.text_field :sub_category_name,  class: "form-control custom-control",  placeholder: "Sub Categories Name"%>
</div>
<%#= f.hidden_field :id, :value => '@sub.id'  %>
<%= f.hidden_field :category_id, :value =>  @sub_categories.category_id %>
<input type = "hidden" name = "subcat_id" value = "<%=@sub_categories.id%>">
<div class="modal-footer text-center">
<%= submit_tag 'Update', :class => "btn btn-primary btn-md"%>
</div>
</div>
<%end%>
</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
$("#edit_sub_categories").validate({
rules: {
"sub_categories[sub_category_name]": {
required: true,
maxlength: 30,
minlength: 2,
lettersonly: true

},
},
messages: {
"sub_categories[sub_category_name]":{
required: "Please enter the sub_category name.",
maxlength: "Maximum  characters are 30.",
minlength: "Minimum characters are 2",
},
},
});

jQuery.validator.addMethod("lettersonly", function(value, element) {
return this.optional(element) || /^[a-z ]+$/i.test(value);
}, "Letters only please"); 
});
</script>

app/views/admin/categories/add_category.html.erb
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<section class="content-header">
  <center>
    <h1><b>Add Categories Details</b></h1>
      <p class="box box-info"></p>
   </center>
</section>
<section class="content">
  <%= nested_form_for :sub_category, url: create_category_details_admin_categories_path, method: :post, local: true do |f| %>
  <div class="row">
     <div class="col-md-3">
     </div>
     <div class="col-md-6">
      <div class="box box">
         <div class="box-body box-profile">

         	<ul class="list-group list-group-unbordered">
               <li class="list-group-item">
                  <b>Category Types</b>
                      <%= f.select("category_type", category, {:include_blank => "category_type"}) %>

                   <b>Sub Category Types</b>
                      <%= f.select("sub_category_type", sub_category, {:include_blank => "sub_category_type"}) %>
                </li>
            </ul>
          <%= f.fields_for :details do |d| %>
           <ul class="list-group list-group-unbordered">
               <li class="list-group-item">
                  <b>Title</b>
                      <%= d.text_field :title, class: 'form-control', autofocus: true, placeholder: "title" %>
				</li>
            </ul>
            <ul class="list-group list-group-unbordered">
               <li class="list-group-item">
                  <b>Description</b>
                      <%= d.cktext_area :description, class: 'form-control', autofocus: true, placeholder: "title" %>
				</li>
            </ul>
             <ul class="list-group list-group-unbordered">
               <li class="list-group-item">
                  <b>Image:</b>
                    <label for="file-upload" class="custom-file-upload ">
						<%= f.fields_for :image_attributes do |m| %>
   							<img src='<%="/assets/user_no_image.png" %>' class="img-circle" alt="Image Not Found" id="user_pic"  onchange = "preview(this)" height=150px width=150px /><i class="fa fa-camera" style="position: absolute; margin-top: 47px; margin-left: -45px; font-size: 24px;" ></i>
							<%= m.file_field :file, onchange: "preview(this)" , accept: "image/*" , style: "display:none" , id: "file-upload"%>
  						<%end%>
  					</label>
				</li>
        <%end%>
            </ul>
            
     <%#= f.link_to_add '<i class="fa fa-plus mt-10 fa-2x" aria-hidden="true"></i>'.html_safe, :details %>
            <div class="form-group has-feedback">
                      <%= f.submit "Submit" , class: "btn btn-success btn-block"%>
                    </div>
          <a href="/admin/users" class="btn btn-danger btn-block"><b>Back</b></a>
        </div>
      </div>
   </div>
  <div class="col-md-3">
  </div>
 </div>
 <%end%>
</section>
<script type="text/javascript">
	function preview(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                  reader.onload = function (e) {
                    $('#user_pic')
                        .attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
</script>

app/views/admin/categories/edit_review_part.js.erb
$("#sub_modal_view1").html("<%= escape_javascript(render("edit_review_part")) %>");

app/views/admin/categories/edit_sub_category.js.erb
$("#sub_modal_view").html("<%= escape_javascript(render("edit_sub_cat")) %>");

app/views/admin/categories/index.html.erb
<section class="content">
      <div class="clearfix">
        <div class="global-heading user-head">Category Management</div>
        <div class="aduser-btn"><a href="/admin/categories/new" class="btn btn-add" title="Add Category"><i class="fa fa-plus"></i> Add Category</a></div>
      </div>
      <div class="clearfix box box-primary">
        <fieldset class="global-fieldset">
        <legend>Filter</legend>
        <div class="filter-form">
        <!-- <form action="/admin/users" method="get" accept-charset="UTF-8" enctype="multipart/form-data" id="web-user-val" class="form-common clearfix"> -->
         <%= form_tag "/admin/categories", method: :get,  class:"form-common clearfix" do  %>
          <div class="col-sm-3">
            <div class="form-group">
              <label>NAME</label>
              <!-- <input type="text" class="form-control custom-control " name="user_name"> -->
              <input type="text" name="search" class="form-control custom-control" placeholder="Search by category name" id="country_serch">
            </div>
          </div>
          <div class="col-sm-3">
            <div class="filter-btn">
              <button class="btn btn-primary" title="Search"> <i class="fa fa-search"></i> Filter </button>
              <a href="/admin/categories" class="btn btn-danger" title="Cancel">Cancel</a>
            </div>
          </div>
        <!-- </form> -->
        <%end%>
      </div>
    </fieldset>
      </div>
     <div id="country-content">
        <%#= render partial: "index"%>
        <div class="clearfix">
        <h3>Category List</h3>
        <div class="table-responsive cus-table">
           <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Sr_No.</th>
                  <!-- <th>ID</th> -->
                  <th>Category name</th>
                  <th colspan="3">Actions</th>
                </tr>
              </thead>
              <tbody>
                 <% if @categories.blank? %>
                      <div class="global-heading user-head">No Record Found. </div>
                   <% else %>
              <% @categories.each do |m| %>
                <tr>
                  <td><%= @s_no += 1 %></td>
                  <!-- <td><%#= m.try(:id)%></td> -->
                  <td><%= m.try(:category_name)%></td>
                  <td><%= link_to '<em class="fa fa-edit" aria-hidden="true"></em>'.html_safe, edit_admin_category_path(m),:class=>"btn btn-success", method: :get, title: "Edit" %>
                  <%= link_to '<em class="fa fa-trash" aria-hidden="true"></em>'.html_safe, admin_category_path(id: m.id),title: "Delete",:data => {:confirm => "Are you sure you want to delete this category ?"},:class=>"btn btn-danger", method: :delete %></td>
                </tr>
              <% end %>
              <%end%>
              </tbody>
            </table>
            
             <%#= will_paginate @categories,  renderer: BootstrapPagination::Rails %>
              <%#= will_paginate @categories %>
          </div>
        </div>
     </div>
    </section>
    <div class="box-footer">
        <div class="digg_pagination pull-right">
                <%= will_paginate @categories %>
        </div>
    </div>

app/views/admin/categories/new.html.erb
<div class="login-part">
	<div class="clearfix">
	  <div class="global-heading user-head">Category Management</div>
	  <div class="aduser-btn"><a href="/admin/categories" class="btn btn-add"> << Back to list </a></div>
	 </div>
  <div class="login-detail createpro-detail1">
    <!-- <form class="form-common"> -->
    <%= form_for :category, url: admin_categories_path, html:  {id: "admin_category"}  do |f| %>
   
      <div class="row">
        <div class="col-sm-12">
          <div class="category_mng-form">
            <div class="form-group">
               <label for="">Category Name<span class="required">*</span> </label>
               <%= f.text_field :category_name, class: "form-control custom-control",  placeholder: "Category Name"%>
            </div>
            
            <div class="form-group">
            	
              <div class="form-add">
                <%= submit_tag 'Submit', :class => "btn btn-primary btn-md"%>
                <a href="/admin/categories" class="btn btn-add btn-danger btn-md ">Back</a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <%##################################################################################3%>
  <!--     <%#= nested_form_for :sub_category, url: create_sub_category_admin_categories_path, method: :post, local: true do |f| %>
       <div class="row">
        <div class="col-sm-12">
          <div class="category_mng-form">
            <div class="form-group">
               <label for="">Sub Category Name<span class="required">*</span> </label>
               <%#= f.text_field :sub_category_name, class: "form-control custom-control",  placeholder: "Sub Category Name"%>
            </div>
            <div class="form-group">
              <div class="form-add">
                <%#= submit_tag 'Submit', :class => "btn btn-primary btn-md"%>
              </div>
            </div>
          </div>
        </div>
      </div>
 <%#end%> -->
    <%###################################################################################%>
    <!-- </form> -->
  </div>
</div>


<script>
// $(document).ready(function() {
//      $("#admin_category").validate({
//     rules: {
//       "category[category_name]": {
//         required: true
        
//       }
 


//     },
//     messages: {
//       "category[category_name]":{
//         required: "Please select the category name.",
//         maxlength: "Maximum characters are 35."
//       }
//     },
//     submitHandler: function(form) {
//       form.submit();
//     }
//    });
   
//    $.validator.addMethod("regxfloat", function(value, element, regexpr) {          
//     return regexpr.test(value);
// }, "Invalid Format");

//    $.validator.addMethod('lessThanEqual', function(value, element, param) {
//     if (this.optional(element)) return true;
//     var i = parseInt(value);
//     // var j = parseInt($(param).val());
//     return i <= 100;
// }, "The value must be less than or equal to {100}.");

// });

</script>

<script>
   // jQuery(document).change('#category_category_name', function(e){
    
  
    $("#category_category_name").change(function(){
   var input_state = $(this).val();
     str = "";
         $.ajax({
              url: "/admin/categories/edit",
               type: 'POST',
               data: {
                       input_state: input_state 
                     },
               dataType: "JSON",
                success: function(response){
                    console.log(response);  
       
                   $.each( response.state , function(i,l){
                      str += '<option value="'+l+'">' + l+'</option>';
                  });
                     $('#state_state_name').empty().append('<option value="">Select State</option>');
                     $('#state_state_name').append(str);
                  }
   
         });
   
              
   
            
      });
   </script>
   <script>
     
  $(document).ready(function() {
    $("#admin_category").validate({
   rules: {
     // "category[category_name]": {
       "category[category_name]": {
       required: true,
       maxlength: 30,
       minlength: 2,
       lettersonly: true
     },
   },
   messages: {
     // "category[category_name]":{
       "category[category_name]": {
       required: "Please select the category name.",
       maxlength: "Maximum  characters are 30.",
       minlength: "Minimum characters are 2",
     },
   },
  });

jQuery.validator.addMethod("lettersonly", function(value, element) {
 return this.optional(element) || /^[a-z ]+$/i.test(value);
}, "Letters only please"); 
  });

</script>

app/views/admin/categories/newold.html.erb
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<section class="content-header">
  <center>
    <h1><b>Add Categories</b></h1>
      <p class="box box-info"></p>
   </center>
</section>
<section class="content">
  <%= nested_form_for @category, url:  admin_categories_path, method: :post, local: true do |f| %>
  <div class="row">
     <div class="col-md-3">
      <%= link_to "Add Details", add_category_admin_categories_path %>
     </div>
     <div class="col-md-6">
      <div class="box box">
         <div class="box-body box-profile">
          
           <ul class="list-group list-group-unbordered">
               <li class="list-group-item">
                  <b>Category</b>
                      <%= f.text_field :category_name, class: 'form-control', autofocus: true, placeholder: "category" %>

               </li>
               <%= f.fields_for :sub_categories do |sub| %>
               <li class="list-group-item">
                   <b>Sub Category</b>
                    <%= sub.text_field :sub_category_name, class: 'form-control', autofocus: true, placeholder: "sub_category" %>
                        


               </li>
              <%end%>
                    <%#= f.link_to_add '<i class="fa fa-plus mt-10 fa-2x" aria-hidden="true"></i>Add Sub-Category'.html_safe, :sub_categories ,id: "add_sub_category"%> 

                     <%= f.link_to_add '<i class="fa fa-plus mt-10 fa-2x" aria-hidden="true"></i>'.html_safe, :sub_categories ,id: "add_product_descriptions" %>
                       
                     <%#= f.link_to_remove '<i class="fa fa-times mt-10 fa-2x" aria-hidden="true"></i>'.html_safe, :sub_categories ,id: "add_product_descriptions" %>

              <p><%#= f.link_to_add "Add a task", :sub_categories %></p>
             
            </ul>
            <div class="form-group has-feedback">
                      <%= f.submit "Submit" , class: "btn btn-success btn-block"%>
                    </div>
          <a href="/admin/users" class="btn btn-danger btn-block"><b>Back</b></a>
        </div>
      </div>
   </div>
  <div class="col-md-3">
  </div>
 </div>
 <%end%>
</section>
 
<script type="text/javascript">
  
	//$('#add_sub_category').on('click',function(){
       // alert(!($('.media_contnt').length < 8));
      // if (!($('input:hidden[name^="campaign[products_attributes][0][medias_attributes]["][id$="_destroy"][value="false"]').length < 7)){
         //$('#add_sub_category').css('display','none');
       //});
     
         // console.log($('.media_contnt').length)    
    $('form').on 'click', '.remove_fields', (event)
    $(this).prev('input[type=hidden]').val('1')
    $(this).closest('fieldset').hide()
    event.preventDefault()

</script>>