config/routes.rb
Rails.application.routes.draw do
  get '/auth/facebook/callback' , to: 'users/sessions#create_user'

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    get 'homes/index'
  end
  #devise_for :users
     devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        omniauth_callbacks: "users/omniauth_callbacks" 
        #registrations: 'users/registrations'
      }


  namespace :web do
    resources :categories do
    collection do
      get :review_system
    end
    end

    resources :reviews do
      collection do
        get :review_chart, to: 'reviews#review_chart', as: 'review_chart'
        post :average_criteria
        post :average_bar_graph_data
        post :get_reviews
        post :get_vote_for_review
      end
    end
    get '/:name' , to: 'users#index' , as: 'users'
    resources :users, except: [:index] do
    collection do
      get :read_full_review
      get :check_email
      get :check_email_login
      post :image_update
      get :report
      get :report_details
      get :header_search
      get :user_score
      get :rating_product
      get :hollframe
      get :user_type
      get :trending
      get :upcomeing
      get :holl_of_fame_details
      get :categorywise
      get :rating_calculate
    end
    member do
      get :blockchain_data
      get :user_profile
      get :movie_category
      get :movie_category_detail
      get :movie_detail
      get :movie_review
      get :full_review
    end
   end 
  end

  namespace :admin do
    resources :users do
      collection do
        post :import
        get :change_admin_password
        # get :feedback
      end
    member do
        get :status
        get :admin_profile
        get :edit_admin_profile
        patch :update_admin_profile
        patch :type_user
        patch :expert_user
        # get :show_feedback
        # delete :destroy_feedback
      end
    end
    resources :faqs
    resources :feedbacks
    resources :static_content
    resources :categories do
      collection do
        get :edit_sub_category
        get :edit_review_part
       delete :destroy_sub_category
       delete :destroy_review_part
        post :create_sub_category
        post :create_post_review
        post :update_sub_category
        post :update_review_part
        get :add_category
        post :create_category_details
        get :search_sub_categories
      end
    end
    resources :products do
      collection do
        get :sub_categories_by_category
      end
      member do 
        patch :publish
        patch :show_in_banner
        get :add_links
        get :new_addlinks
        post :create_product_link
        delete :product_link_delete
        patch :unpublish
        patch :trending
      end
    end
      get 'homes/index', as: "home_index"
  end
   resources :homes do
      collection do
        get :about_us
        get :faq
        get :privacy_policy
        get :term_condition
        get :feedback
        get :contact_us
      end
    end
    root :to =>  "web/users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :users do
        collection do
            post :sign_up
            
        end 
      end
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
    attr_accessor :user_type
	mount_uploader :video, ImageUploader
	# mount_uploader :file, ImageUploader
	belongs_to :sub_category 
    belongs_to :category
    has_many :product_links, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :image, class_name: 'Image', as: :imageable, autosave: true, dependent: :destroy
    accepts_nested_attributes_for :image, allow_destroy: true
    validates :product_name, presence: true
    validates :category_name, presence: true
    # validates :product_name, length: { minimum: 3, maximum: 20}
    # validates :product_name, format: { with: /[a-zA-Z]/, message: "%{value} not accecpt. Only allows character" }
    validates :description, length: { minimum: 20, maximum: 2000}

    scope :published_products , -> { where(current: "publish").order("created_at DESC") }
    #validates :product_name, format: { with: /\A[a-zA-Z]+\z/, message: "%{value} not accecpt. Only allows letters" }
    def average_criteria_by_product        
        Review.average_criteria_by_product self.id , self.user_type
    end

    def average_criteria_by_category
        Review.average_criteria_by_category self.id , self.user_type
    end

    def average_criteria_by_sub_cat
        Review.average_criteria_by_product self.id , self.user_type
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
	before_action :authenticate_user!	
  before_action :find_products, only: [:show, :edit, :update, :destroy] 
  layout 'admin_lte_2'

    def index
      @s_no = 0
      if params[:search].present?
         @products = Product.where("product_name ILIKE ?", "%#{params[:search]}%")
         @products = @products.order("created_at desc").paginate(:page => params[:page], :per_page => 100)
      else
      @products = Product.order("created_at desc").paginate(:page => params[:page], :per_page => 10)
      @category = Category.all
      end
    end

    def new
      @products = Product.new
      @products.image&.build
    end

    def add_links
       @s_no = 0
       # binding.pry
    if params[:search].present?
       @categories = Category.where(category_name: params[:search])
       @categories = @categories.order("created_at desc").paginate(:page => params[:page], :per_page => 100)
    else
        @product_links = Product.find_by(id:params[:id]).product_links
        @products_link = @product_links.order("created_at desc").paginate(:page => params[:page], :per_page => 8)
    end
    end

    def show
     @images = @products.image.all
      @category=Category.find(@products.category_id)
    @sub_category=SubCategory.find(@products.sub_category_id)
    end
     
    def edit
    @images = @products.image.all
    @sub_categories =@products.category.sub_categories.pluck("sub_category_name")
    end

    def create
      @products = Product.where(category_name: params[:product][:category_name], sub_category_name: params[:product][:sub_category_name], product_name: params[:product][:product_name])
      if @products.present?
         flash[:notice] = "Product name is all ready created for the same category and sub category name"
      else
      @products = Product.new(product_params)
      @products.category_id = Category.find_by(category_name: params[:product][:category_name]).id
      @products.sub_category_id = SubCategory.find_by(sub_category_name: params[:product][:sub_category_name]).id
      if params[:product][:date].present?
        x=params[:product][:date][0,2]
        params[:product][:date][0,2]= params[:product][:date][3,2]
        params[:product][:date][3,2]=x
        @products.date = params[:product][:date]
      end
      if @products.save!   
        # productCount = 0
        contract_instance.transact_and_wait.add_product(@products.product_name,@products.category_id) rescue nil
         count = contract_instance.call.product_count - 1 rescue 0
        # productCount = Product.maximum(:product_blockchain_id) + 1 rescue 0
        @products.update!(product_blockchain_id: count)
        # productCount +=1
        redirect_to admin_products_path(@products)
        flash[:notice] = "product created succesfull"
       else
          flash[:alert] = @products.errors.full_messages
       	  redirect_to new_admin_product_path
       	  flash[:notice] = "product not created" 
       end
     end
    end
    
   def destroy
      if @products.destroy
             redirect_to admin_products_path
          else
             redirect_to admin_products_path
      end
   end

    def update
      @products.update(category_id: Category.find_by(category_name: params[:product][:category_name]).id)
      @products.update(sub_category_id: SubCategory.find_by(sub_category_name: params[:product][:sub_category_name]).id)
      if params[:product][:date].size == 10
      x=params[:product][:date][0,2]
      params[:product][:date][0,2]= params[:product][:date][3,2]
      params[:product][:date][3,2]=x
      @products.date = params[:product][:date]
    else
      @products.date = params[:product][:date]
    end
        if @products.update_attributes(product_params)
            redirect_to admin_products_path, notice: 'Products Updated Successfully.'
          else
               flash[:notice] = @products.errors.full_messages
               render 'edit'
          end
        end
    

    def sub_categories_by_category 
     product =Category.find_by(category_name: params[:id]).sub_categories
     render json: product
    end
 
   def publish
    Product.find_by(id: params[:id]).update(current: "unpublish")
    redirect_to admin_products_path
      flash[:notice] = "Unpublish mode Successfully"
   end
   
   def show_in_banner
     @show_in_banner=Product.find_by(id: params[:id]).show_in_banner
   if @show_in_banner == true
     Product.find_by(id: params[:id]).update(show_in_banner: false)
      redirect_to admin_products_path
     flash[:notice] = "Product will not show in banner"
    else
     Product.find_by(id: params[:id]).update(show_in_banner: true)
      redirect_to admin_products_path
     flash[:notice] = "Product will show in banner"
   end
   end

   def unpublish
    Product.find_by(id: params[:id]).update(current: "publish")
    redirect_to admin_products_path
    flash[:notice] = "Publish mode Successfully"
   end

   def trending
   @trending=Product.find_by(id: params[:id]).trending
   if @trending == true
     Product.find_by(id: params[:id]).update(trending: false)
      redirect_to admin_products_path
     flash[:notice] = "Product is not trending"
    else
     Product.find_by(id: params[:id]).update(trending: true)
      redirect_to admin_products_path
     flash[:notice] = "Product is trending"
   end
 end
 
 def new_addlinks
 end

 def create_product_link
  @products=Product.find_by(id: params[:id])
  @products.product_links.create(product_link)
  redirect_to add_links_admin_product_path(params[:id])
 end

def product_link_delete
  ProductLink.find_by(id: params[:id]).destroy
  redirect_to admin_products_path
   end

 private
 def product_params 
 	params.require(:product).permit(:category_name, :sub_category_name, :product_name, :video, :date, :description, image_attributes: [:id, :file, :_destroy, :file_type,:avtar])
 end
 
 def find_products
    @products = Product.find_by(id: params[:id])
    redirect_to admin_products_path unless @products
 end
 def product_link
  params.require(:category).permit(:link,:url)
 end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
	def all_category
		Category.all.pluck("category_name")
	end
	def all_sub_category
		SubCategory.all.pluck("sub_category_name")
	end

	 def sub_categories_by_category
	 	
	 	product =Category.find_by(category_name: params[:id]).sub_categories
	 end
end

app/views/admin/products/_formedit.html.erb
<section class="content-header">
    <h1>Edit Products</h1>
</section>
  <section class="content">
    <div class="box box-info">
    <div class="box-body">
      <div class="tab-content">
          <div class="tab-pane fade active in" id="default-tab-1">
            <div class="tab-pane">
                <%= nested_form_for @products, url: admin_product_path, method: :patch, html:  {id: "admin_new_product"}  do |f| %>
                  <div class="detail-form m-t-40 m-b-40">
                    <div class="form-group">
                      <div class="row">
                        <label class="col-sm-2 col-md-2 control-label">Category</label>
                        <div class="col-sm-8 col-md-8">
                             <%#= hidden_field_tag @id = user.id %>
                          <%= f.select :category_name, Category.all.collect {|p| [p.category_name] }, {:include_blank => "Select Category Name" },{:class => "form-control shubham" , id: "category_name_ajax",:required => true} %>
                        </div>
                          <%#= f.hidden_field :category_id, :value =>  @category.id %>
                      </div>
                    </div>
                    <div class="form-group">
                                         <%# @sub_category.each do |faqs| %>
                      <div class="row">
                        <%#=sub_categories_by_category%>
                        <label class="col-sm-2 col-md-2 control-label">Sub_category</label>
                        <div class="col-sm-8 col-md-8">
                          <%#= f.select :state, options_for_select([],@user.state), {:include_blank => "Select State"}, {:id=>"web-user-city-select",:class => "form-control mt-10"} %>
                        <%= f.select :sub_category_name, options_for_select( @sub_categories,@products.sub_category_name), {:include_blank => "Select SubCategory Name"}, {:class => "form-control select-dropdown " ,id: "ror_shubham",:required => true} %>
                        </div>
                      </div>
                    </div>
                     <div class="form-group">
                      <div class="row">
                        <label class="col-sm-2 col-md-2 control-label">Product Name</label>
                        <div class="col-sm-8 col-md-8">
                        <%= f.text_field :product_name, class: "form-control", placeholder: "Product Name",:required => true %>
                        </div>
                      </div>
                    </div>
                     <div class="form-group">
                      <div class="row">
                        <label class="col-sm-2 col-m d-2 control-label">Image</label>
                        <div class="col-sm-8 col-md-8">
                        <label for="file-upload" class="custom-file-upload ">
                            <%= f.fields_for :image do |m| %>

                          <!-- <img src="/assets/photo_gallery.webp"  alt="Image Not Found" id="user_pic"  onchange = "preview(this)" height=100px width=200px /><i class="" style="position: absolute; margin-top: 47px; margin-left: -45px; font-size: 24px;" ></i> -->
                            <%#= m.file_field :file, onchange: "preview(this)" , accept: "image/*", id: "file-upload"%>
                            <div id="file1">
                               <%#= image_tag ((m.object.image.present? && m.object.image_url.present?) ? m.object.image_url : "/assets/photo_gallery.webp" ) %>
                               <img src='<%= m.object.file.present? ? m.object.file_url : "/assets/photo_gallery.webp" %>' height=100px width=200px alt="your image" class="img_prev"/>
                              <%= m.file_field :file, onchange:"readURL(this);", height: "100px;", width: "200px;", accept: "image/*", id: "file-upload", style: ""%>
                              <%= m.check_box :file_type %><b>Header Image</b>
                              <%= m.check_box :avtar %><b>Avatar Image</b>
                                 <!-- <input type='file' onchange="readURL(this);" />  -->
                          
                               </div>
                               <p style="margin-left: -25px;">
                             <%= m.link_to_remove '<i class="fa fa-times fa-2x mt-10" aria-hidden="true"></i>'.html_safe, class: "btn btn-danger margin"%>
                             </p>
                          <%end%>
                       </label>
                       <p><%= f.link_to_add '<i class="fa fa-plus fa-2x mt-10" aria-hidden="true"></i>'.html_safe, :image, class: "btn btn-primary" %></p>
                        </div>
                      </div>
                    </div>
                     <div class="form-group">
                      <div class="row">
                        <label class="col-sm-2 col-md-2 control-label">Video</label>
                        <div class="col-sm-8 col-md-8">
                          <%if @products.video_url.present? %>
                        <%= video_tag  @products.video_url, controls: true, autoplay: false, width: "400px", height: "200px", id: "video_player" %>
                        <%= f.file_field :video, id:"video_file", type:"file", accept:"video/*" %>
                        <%else%>
                        <video id="video_player" width="400" controls></video>
                          <%= f.file_field :video, id:"video_file", type:"file" ,:value => @products&.video_url.present? ? @products&.video_url : "",  accept:"video/*" %>
                         <%end%>
                        </div>
                      </div>
                    </div>
                     <div class="form-group">
                      <div class="row">
                         <label class="col-sm-2 col-md-2 control-label">Launching/Release Date</label>
                        <div class="col-sm-8 col-md-8">
                        <div class="input-group date">
                        <div class="input-group-addon">
                        <em class="fa fa-calendar"></em>
                        </div>
                    <%#= f.text_field :date ,class: "form-control datetimepicker_start",placeholder:"Select Date",data: { provide: 'datepicker',:required => true} %>
                      <%= f.text_field :date ,class: "form-control datetimepicker_start",placeholder:"Select Date", id: "start_date" %>
                        </div>
                        </div>
                      </div>
                    </div>
                     <div class="form-group">
                      <div class="row">
                        <label class="col-sm-2 col-md-2 control-label">Description</label>
                        <div class="col-sm-8 col-md-8">
                         <%= f.cktext_area :description, class: "form-control", placeholder: "" %>
                        </div>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="text-center attendee-cent-s">
                        <button class="btn btn-success" type="submit">Submit</button>
                        <a href="/admin/products" class="btn btn-danger">Cancel</a>
                      </div>
                  </div>
                </div>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

<script type="text/javascript">
  //debugger;
  //
  //
  function readURL(input) {
 if (input.files && input.files[0]) {
 var reader = new FileReader();
 reader.onload = function (e) {
 $(input).parent().find('.img_prev') //finds the parent div and gets the img_prev contained inside 
.attr('src', e.target.result) 
.width(150) 
.height(200);
 }; 
reader.readAsDataURL(input.files[0]); } 
} 
  // function preview(input) {
  //          if (input.files && input.files[0]) {
  //              var reader = new FileReader();
  //                reader.onload = function (e) {
  //                 debugger;
  //                  $('#user_pic')
  //                      .attr('src', e.target.result);
  //              };

  //              reader.readAsDataURL(input.files[0]);
  //          }
  //      }
       
       $(document).ready(function(){
  //alert("hello bhai");
  $('#1').click();

 
  $('.shubham').change(function(){
    // debugger;
    var id=this.value;
    $.ajax({
         url: '/admin/products/sub_categories_by_category',
         type: 'get',
         data: {
          id: id
         },

         success: function(result){
          var newOptions = result;
          $('#ror_shubham').empty();
          var sub_category = $('#ror_shubham');
          $.each(newOptions, function(key,value) {
              sub_category.append($("<option></option>").attr("value", value.sub_category_id).text(value.sub_category_name));
          });
        }
        
      });
    });
 });

</script>
<style type="text/css">
  select {
    width: 795px;
}
.margin {
  margin: 10px;
  margin-left: 235px;
  margin-top: -150px;
}
input[type="file"] {
  display: block;
  margin-top: 10px;
}

</style>
<script type="text/javascript">
  video_file.onchange = function(){
    var files = this.files;
    var file = URL.createObjectURL(files[0]); 
    video_player.src = file; 
    video_player.play();
};
</script>
<script type="text/javascript">
  $(".datetimepicker_start").datepicker({
   autoclose: true,
   minDate: 0,

});

$(function() {
 $(".datetimepicker_start").on('change', function(){
        var date = Date.parse($(this).val());
        if (date < Date.now()){
            alert('Publish Date should be proper format and not of past');
            $(this).val('');
        }


   });

});
</script>

app/views/admin/products/add_links.html.erb
<section class="content">
      <div class="clearfix">
        <div class="global-heading user-head">Link Management</div>
        <!-- <div class="aduser-btn"><a href="/admin/products/new_addlinks(params[:id])" class="btn btn-add" title="Add Category"><i class="fa fa-plus"></i> Add Link</a></div> -->
        <div class="aduser-btn"><%= link_to "Add Title/link",new_addlinks_admin_product_url(params[:id]) ,class: "btn btn-add"%></div>
      </div>
     <!--  <div class="clearfix box box-primary">
        <fieldset class="global-fieldset">
        <legend>Filter</legend>
        <div class="filter-form">
         <%#= form_tag "/admin/products/add_links", method: :get,  class:"form-common clearfix" do  %>
          <div class="col-sm-3">
            <div class="form-group">
              <label>NAME</label>
              <input type="text" name="search" class="form-control custom-control" placeholder="Search by category name" id="country_serch">
            </div>
          </div>
          <div class="col-sm-3">
            <div class="filter-btn">
              <button class="btn btn-primary" title="Search"> <i class="fa fa-search"></i> Filter </button>
              <a href="/admin/categories" class="btn btn-danger" title="Cancel">Cancel</a>
            </div>
          </div>
        <%#end%>
      </div>
    </fieldset>
      </div> -->
     <div id="country-content">
        <%#= render partial: "index"%>
        <div class="clearfix">
        <h3> Product Link List</h3>
        <div class="table-responsive cus-table">
           <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Sr_No.</th>
                  <!-- <th>ID</th> -->
                  <th>Title</th>
                  <th>Url</th>
                  <th colspan="3">Actions</th>
                </tr>
              </thead>
              <tbody>
                 <% if @product_links.blank? %>
                      <div class="global-heading user-head">No Record Found. </div>
                   <% else %>
                   <%#binding.pry%>
              <% @product_links.each do |m| %>
                <tr>
                  <td><%= @s_no += 1 %></td>
                  <!-- <td><%#= m.try(:id)%></td> -->
                  <td><%= m.try(:link)%></td>
                  <td><%= m.try(:url)%></td>
                  <td><%#= link_to '<em class="fa fa-edit" aria-hidden="true"></em>'.html_safe, edit_admin_category_path(m),:class=>"btn btn-success", method: :get, title: "Edit" %>
                  <%= link_to '<em class="fa fa-trash" aria-hidden="true"></em>'.html_safe, product_link_delete_admin_product_path(id: m.id),title: "Delete",:data => {:confirm => "Are you sure you want to delete this Link ?"},:class=>"btn btn-danger", method: :delete %></td>
                </tr>
              <% end %>
              <%end%>
              </tbody>
            </table>
            
             <%#= will_paginate @categories,  renderer: BootstrapPagination::Rails %>
              <%#= will_paginate @categories %>
          </div>
        </div>
     </div>
    </section>
    <div class="box-footer">
        <div class="digg_pagination pull-right">
                <%= will_paginate @products_link %>
        </div>
    </div>

app/views/admin/products/edit.html.erb
<%= render 'formedit'%>

app/views/admin/products/index.html.erb
<div class="content-wrapper2">
   <!-- Content Header (Page header) -->
   <section class="content-header">
      <div class="clearfix">
        <div class="global-heading user-head">Product Management</div>
        <div class="aduser-btn"><a href="/admin/products/new" class="btn btn-add" title="Add Product"><i class="fa fa-plus"></i> Add product</a></div>
      </div>
      <div class="clearfix box box-primary">
        <fieldset class="global-fieldset">
        <legend>Filter</legend>
        <div class="filter-form">
        <!-- <form action="/admin/users" method="get" accept-charset="UTF-8" enctype="multipart/form-data" id="web-user-val" class="form-common clearfix"> -->
         <%= form_tag "/admin/products", url: admin_products_path, method: :get,  class:"form-common clearfix" do  %>
          <div class="col-sm-3">
            <div class="form-group">
              <label>NAME</label>
              <!-- <input type="text" class="form-control custom-control " name="user_name"> -->
              <input type="text" name="search" class="form-control custom-control" placeholder="Search by Product/Category/Sub_Category Name" id="country_serch">
            </div>
          </div>
          <div class="col-sm-3">
            <div class="filter-btn">
              <button class="btn btn-primary" title="Search"> <i class="fa fa-search"></i> Filter </button>
              <a href="/admin/products" class="btn btn-danger" title="Cancel"> Cancel</a>
            </div>
          </div>
        <!-- </form> -->
        <%end%>
      </div>
    </fieldset>
      </div>
   </section>
   <!-- Main content -->

   <section class="content">
    <div class="box box-info">
           <div class="box-body">
           <div class="table-responsive ">
             <table id="example2" class="table table-bordered table-hover ">
               <thead>
                 <tr style="background-color: #D9D7D7;">
                <th>Sr_No.</th>
           		  <th>Product Name</th>
                <th>Category Name</th>
           		  <th>SubCategory Name</th>
           		  <th>Trending</th>
           		  <th>Action</th>
           			</tr>
               </thead>
                <% if @products.blank? %>
                      <div class="global-heading user-head">No Record Found. </div>
                   <% else %>
               <% @products.each do |product| %>
           			<% unless product.eql?(nil) %>
           				<tbody>
           					<tr class="even">
                      <td><%= @s_no += 1 %></td>
           						<td><%= product.product_name %></td>
                      <td><%= product&.category_name %></td>
                      <td><%= product&.sub_category_name %></td>
           						<td><% if product.trending == true %>
                      <%= link_to 'Yes'.html_safe,trending_admin_product_path(product.id), method: :patch, class: "btn btn-success", title: "Trending", data: {confirm: "Are you sure want this product is trending"} %>
                        <%else%>
                        <%= link_to 'NO'.html_safe,trending_admin_product_path(product.id), method: :patch, class: "btn btn-danger", title: "Not a Trending", data: {confirm: "Are you sure want to this product is not trending"} %>
                      <%end%>
                      </td>
           						<td class="cell-action-btn">
                         <a href="/admin/products/<%= product.id %>" class="btn btn-success"><em class="fa fa-eye" aria-hidden="true" title="View"></em></a> 
           							<a href="/admin/products/<%= product.id%>/edit" class="btn btn-primary"><em class="fa fa-edit" aria-hidden="true" title="Edit"></em></a>
           							<a>
           							<%= link_to '<em class="fa fa-trash" aria-hidden="true"></em>'.html_safe,  admin_product_path(product.id), method: :delete,:class=>"btn btn-danger",title: "Delete", data: {confirm: 'Are you sure want to delete this Product?' }%></a>
                        <% if product.current == "publish" %>
                       <%= link_to 'Publish'.html_safe, publish_admin_product_path(product), method: :patch, class: "btn btn-warning", title: "Publish Mode", data: {confirm: "Are you sure want to be change the Unpublish mode"} %>
                       <%else%>
                        <%= link_to "Unpublish".html_safe, unpublish_admin_product_path(product), method: :patch, class: "btn btn-success", id: 'btnsubmit', title: "Unpublish Mode", data: {confirm: "Are you sure want to be change the publish mode"} %>
                         <%end%>
                       <!-- </td>
                       <td> -->
                         <%= link_to "Add Title/Links".html_safe, add_links_admin_product_path(product), method: :get, class: "btn btn-success", id: 'btnsubmit' %>
                         <% if product.show_in_banner == true %>
                       <%= link_to 'Show in Banner'.html_safe, show_in_banner_admin_product_path(product), method: :patch, class: "btn btn-warning", title: "Show in Banner  Mode", data: {confirm: "Are you sure you Don't want to  Show in Banner."} %>
                       <%else%>
                        <%= link_to "Don't Show in Banner".html_safe, show_in_banner_admin_product_path(product), method: :patch, class: "btn btn-success", id: 'btnsubmit', title: "Don't Show in Banner  Mode", data: {confirm: "Are you sure you want to  Show in Banner."} %>
                         <%end%>
                       </td>
           					</tr>
           				</tbody>
           			<%end%>
                <%end%>
           		<%end%>
           	</table>
            </div>
             <div class="digg_pagination pull-right">
                    <%= will_paginate @products %>
            </div>
           </div>
         </div>
   </section>
 </div>
 

app/views/admin/products/new.html.erb
<%= render 'form'%>

app/views/admin/products/new_addlinks.html.erb
<div class="login-part">
	<div class="clearfix">
	  <div class="global-heading user-head">Product Title/Link Management</div>
	  <div class="aduser-btn"><a href="/admin/products" class="btn btn-add"> << Back to list </a></div>
	 </div>
  <div class="login-detail createpro-detail1">
    <!-- <form class="form-common"> -->
    <%= form_for :category, url: create_product_link_admin_product_path(params[:id]), html:  {id: "admin_category"}  do |f| %>
   
      <div class="row">
        <div class="col-sm-12">
          <div class="category_mng-form">
            <div class="form-group">
               <label for="">Title<span class="required">*</span> </label>
               <%= f.text_field :link, class: "form-control custom-control",  placeholder: "Add Title"%>
            </div>

            <div class="form-group">
               <label for="">Url<span class="required">*</span> </label>
               <%= f.text_field :url, class: "form-control custom-control",  placeholder: "Add Url"%>
            </div>
            
            <div class="form-group">
            	
              <div class="form-add">
                <%= submit_tag 'Submit', :class => "btn btn-primary btn-md"%>
                <a href="/admin/products" class="btn btn-add btn-danger btn-md ">Back</a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>