config/routes.rb
Rails.application.routes.draw do
  get '/auth/facebook/callback' , to: 'users/sessions#create_user'

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    get 'homes/index'
  end
  #devise_for :users
     devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        omniauth_callbacks: "users/omniauth_callbacks" 
        #registrations: 'users/registrations'
      }


  namespace :web do
    resources :categories do
    collection do
      get :review_system
    end
    end

    resources :reviews do
      collection do
        get :review_chart, to: 'reviews#review_chart', as: 'review_chart'
        post :average_criteria
        post :average_bar_graph_data
        post :get_reviews
        post :get_vote_for_review
      end
    end
    get '/:name' , to: 'users#index' , as: 'users'
    resources :users, except: [:index] do
    collection do
      get :read_full_review
      get :check_email
      get :check_email_login
      post :image_update
      get :report
      get :report_details
      get :header_search
      get :user_score
      get :rating_product
      get :hollframe
      get :user_type
      get :trending
      get :upcomeing
      get :holl_of_fame_details
      get :categorywise
      get :rating_calculate
    end
    member do
      get :blockchain_data
      get :user_profile
      get :movie_category
      get :movie_category_detail
      get :movie_detail
      get :movie_review
      get :full_review
    end
   end 
  end

  namespace :admin do
    resources :users do
      collection do
        post :import
        get :change_admin_password
        # get :feedback
      end
    member do
        get :status
        get :admin_profile
        get :edit_admin_profile
        patch :update_admin_profile
        patch :type_user
        patch :expert_user
        # get :show_feedback
        # delete :destroy_feedback
      end
    end
    resources :faqs
    resources :feedbacks
    resources :static_content
    resources :categories do
      collection do
        get :edit_sub_category
        get :edit_review_part
       delete :destroy_sub_category
       delete :destroy_review_part
        post :create_sub_category
        post :create_post_review
        post :update_sub_category
        post :update_review_part
        get :add_category
        post :create_category_details
        get :search_sub_categories
      end
    end
    resources :products do
      collection do
        get :sub_categories_by_category
      end
      member do 
        patch :publish
        patch :show_in_banner
        get :add_links
        get :new_addlinks
        post :create_product_link
        delete :product_link_delete
        patch :unpublish
        patch :trending
      end
    end
      get 'homes/index', as: "home_index"
  end
   resources :homes do
      collection do
        get :about_us
        get :faq
        get :privacy_policy
        get :term_condition
        get :feedback
        get :contact_us
      end
    end
    root :to =>  "web/users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :users do
        collection do
            post :sign_up
            
        end 
      end
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminApplicationController
 before_action :authenticate_user!
 before_action :find_content, only: [:show,:edit,:update,:status,:destroy,:update_admin_profile]
 layout 'admin_lte_2'
 
    def index
        @sr_no = 0
        @search = User.where(role: "user").order("created_at desc").paginate(:page => params[:page], :per_page => 5)
        @users_count = @search.count
        @users = user_search
        respond_to do |format|
           format.html
           format.csv { send_data @users.to_csv }
        end

        @users = @users.decorate
    end

    
   
    def show
  	     @users = User.decorate
    end

    

    def edit
    end

    def type_user
      @normal_user = User.find_by(id: params[:id]).update(user_type: "Normal User")
      redirect_to admin_users_path
      flash[:notice] = "User Type (Normal User) Change Succesfully"
    end

    def expert_user
      @expert_user = User.find_by(id: params[:id]).update(user_type: "Expert User")
      redirect_to admin_users_path
      flash[:notice] = "User Type (Expert User) Change Successfully"
    end
   
    def import
       User.import(params[:file])
       redirect_to admin_users_path
       flash[:notice] = "File Import Successfully"
    end
  

    def update
        if @user.update_attributes(user_params)
          if @user.image.present?
                 @user.image.update(file: params[:user][:image])
                 @user.update(user_type: params[:user][:user_type])
                 redirect_to admin_users_path
                 flash[:notice] = "User Profile Update Successfully"
             else
                 @user.create_image(file: params[:user][:image])
                 @user.update(user_type: params[:user][:user_type])
                 redirect_to admin_users_path
                 flash[:notice] = "User Profile Update Succesfully"
          end
        else
           flash[:alert] = @user.errors.full_messages
           flash[:notice] = "User Profile Not Update."
           redirect_to admin_users_path
        end
    end
  
   def destroy
    if @user.destroy
      redirect_to  admin_users_path
      flash[:notice] = 'User Deleted Successfully'
    else
      flash[:error] = @user.errors.full_messages.first
      redirect_to  admin_users_path
      flash[:notice] = 'User Not Delete'
    end
   end

   def admin_profile
      @user = User.find_by(id: params[:id])
   end

  def edit_admin_profile
    @user = User.find_by(id: params[:id])
  end

  def update_admin_profile
      if @user.update_attributes(admin_params)
      if @user.image.present?
             @user.image.update(file: params[:user][:image])
             redirect_to admin_users_path
             flash[:notice] = "Admin Profile Update Successfully"
         else
             @user.create_image(file: params[:user][:image])
             redirect_to admin_users_path
             flash[:notice] = "Admin Profile Update Succesfully"
      end
     else
         flash[:notice] = "Admin profile not update."
         redirect_to admin_profile_admin_user_path
     end
  end
    
 def status 
      @user.status? ? @user.update(status: false) : @user.update(status: true)
      flash[:notice] = "User status changed successfully."
      redirect_back(fallback_location: admin_users_path)
  end
   
private
  def find_content
    @user = User.find_by(id: params[:id])
    redirect_to admin_users_path unless @user
  end
  def user_params
    params.require(:user).permit(:name, :mobile_no)
  end
  def admin_params
    params.require(:user).permit(:name, :mobile_no)
  end
  
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController

	def sign_up
    
    @user = User.find_by(email: params["user"][:email].try(:downcase)) if params["user"][:email].present?
    return render json: {responseCode: 402, responseMessage: "User already exist."} if @user.present?
    if params["user"][:password] != params["user"][:password_confirmation] 
      return render json: {responseCode: 402, responseMessage: "Password doesn't matched."}
    end
	 @user = User.new(user_params)
	  if @user.save!
	    device = @user.devices.create(device_params) 
      # UserMailer.registration_confirmation(@user).deliver!
      @selected = @user.slice(:id, :email, :access_token, :name)
      render :json =>  {:responseCode => 200,:responseMessage => 'Registration successfully', :user => @selected}

    else
      render :json =>  {:responseCode => 500,:responseMessage => @user.errors.full_messages.first }	  
    end
	end

 



 private

  def authentication_failed
  	render json: {responseCode: 403, responseMessage: ('Please check your email/password.')}
  end
  
  def user_params
  	password = params[:password]
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
    

  def device_params
    params.require(:device).permit(:device_type, :device_token)
  end	


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end
   def facebook
   @user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
      session[:user_id] = @user.id
      # WelcomeJob.perform_later
      sign_in_and_redirect @user
      # redirect_to root_path#(id: @user.id)
  end
  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  def create_user
   @user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
      # session[:user_id] = @user.id
      # WelcomeJob.perform_later
      redirect_to root_path#(id: @user.id)
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  #If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
	 def all_iso_codes
		{
		"+93(AF)": "+93",
		"+358(AX)": "+358",
		"+355(AL)": "+355",
		"+213(DZ)": "+213",
		"+1684(AS)": "+1684",
		"+376(AD)": "+376",
		"+244(AO)": "+244",
		"+1264(AI)": "+1264",
		"+672(AQ)": "+672",
		"+1268(AG)": "+1268",
		"+54(AR)": "+54",
		"+374(AM)": "+374",
		"+297(AW)": "+297",
		"+61(AU)": "+61",
		"+43(AT)": "+43",
		"+994(AZ)": "+994",
		"+1242(BS)": "+1242",
		"+973(BH)": "+973",
		"+880(BD)": "+880",
		"+1246(BB)": "+1246",
		"+375(BY)": "+375",
		"+32(BE)": "+32",
		"+501(BZ)": "+501",
		"+229(BJ)": "+229",
		"+1441(BM)": "+1441",
		"+975(BT)": "+975",
		"+591(BO)": "+591",
		"+387(BA)": "+387",
		"+267(BW)": "+267",
		"+55(BR)": "+55",
		"+246(IO)": "+246",
		"+673(BN)": "+673",
		"+359(BG)": "+359",
		"+226(BF)": "+226",
		"+257(BI)": "+257",
		"+855(KH)": "+855",
		"+237(CM)": "+237",
		"+1(CA)": "+1",
		"+238(CV)": "+238",
		"+(KY) 345": "+ 345",
		"+236(CF)": "+236",
		"+235(TD)": "+235",
		"+56(CL)": "+56",
		"+86(CN)": "+86",
		"+61(CX)": "+61",
		"+61(CC)": "+61",
		"+57(CO)": "+57",
		"+269(KM)": "+269",
		"+242(CG)": "+242",
		"+243(CD)": "+243",
		"+682(CK)": "+682",
		"+506(CR)": "+506",
		"+225(CI)": "+225",
		"+385(HR)": "+385",
		"+53(CU)": "+53",
		"+357(CY)": "+357",
		"+420(CZ)": "+420",
		"+45(DK)": "+45",
		"+253(DJ)": "+253",
		"+1767(DM)": "+1767",
		"+1849(DO)": "+1849",
		"+593(EC)": "+593",
		"+20(EG)": "+20",
		"+503(SV)": "+503",
		"+240(GQ)": "+240",
		"+291(ER)": "+291",
		"+372(EE)": "+372",
		"+251(ET)": "+251",
		"+500(FK)": "+500",
		"+298(FO)": "+298",
		"+679(FJ)": "+679",
		"+358(FI)": "+358",
		"+33(FR)": "+33",
		"+594(GF)": "+594",
		"+689(PF)": "+689",
		"+241(GA)": "+241",
		"+220(GM)": "+220",
		"+995(GE)": "+995",
		"+49(DE)": "+49",
		"+233(GH)": "+233",
		"+350(GI)": "+350",
		"+30(GR)": "+30",
		"+299(GL)": "+299",
		"+1473(GD)": "+1473",
		"+590(GP)": "+590",
		"+1671(GU)": "+1671",
		"+502(GT)": "+502",
		"+44(GG)": "+44",
		"+224(GN)": "+224",
		"+245(GW)": "+245",
		"+595(GY)": "+595",
		"+509(HT)": "+509",
		"+379(VA)": "+379",
		"+504(HN)": "+504",
		"+852(HK)": "+852",
		"+36(HU)": "+36",
		"+354(IS)": "+354",
		"+91(IN)": "+91",
		"+62(ID)": "+62",
		"+98(IR)": "+98",
		"+964(IQ)": "+964",
		"+353(IE)": "+353",
		"+44(IM)": "+44",
		"+972(IL)": "+972",
		"+39(IT)": "+39",
		"+1876(JM)": "+1876",
		"+81(JP)": "+81",
		"+44(JE)": "+44",
		"+962(JO)": "+962",
		"+77(KZ)": "+77",
		"+254(KE)": "+254",
		"+686(KI)": "+686",
		"+850(KP)": "+850",
		"+82(KR)": "+82",
		"+965(KW)": "+965",
		"+996(KG)": "+996",
		"+856(LA)": "+856",
		"+371(LV)": "+371",
		"+961(LB)": "+961",
		"+266(LS)": "+266",
		"+231(LR)": "+231",
		"+218(LY)": "+218",
		"+423(LI)": "+423",
		"+370(LT)": "+370",
		"+352(LU)": "+352",
		"+853(MO)": "+853",
		"+389(MK)": "+389",
		"+261(MG)": "+261",
		"+265(MW)": "+265",
		"+60(MY)": "+60",
		"+960(MV)": "+960",
		"+223(ML)": "+223",
		"+356(MT)": "+356",
		"+692(MH)": "+692",
		"+596(MQ)": "+596",
		"+222(MR)": "+222",
		"+230(MU)": "+230",
		"+262(YT)": "+262",
		"+52(MX)": "+52",
		"+691(FM)": "+691",
		"+373(MD)": "+373",
		"+377(MC)": "+377",
		"+976(MN)": "+976",
		"+382(ME)": "+382",
		"+1664(MS)": "+1664",
		"+212(MA)": "+212",
		"+258(MZ)": "+258",
		"+95(MM)": "+95",
		"+264(NA)": "+264",
		"+674(NR)": "+674",
		"+977(NP)": "+977",
		"+31(NL)": "+31",
		"+599(AN)": "+599",
		"+687(NC)": "+687",
		"+64(NZ)": "+64",
		"+505(NI)": "+505",
		"+227(NE)": "+227",
		"+234(NG)": "+234",
		"+683(NU)": "+683",
		"+672(NF)": "+672",
		"+1670(MP)": "+1670",
		"+47(NO)": "+47",
		"+968(OM)": "+968",
		"+92(PK)": "+92",
		"+680(PW)": "+680",
		"+970(PS)": "+970",
		"+507(PA)": "+507",
		"+675(PG)": "+675",
		"+595(PY)": "+595",
		"+51(PE)": "+51",
		"+63(PH)": "+63",
		"+872(PN)": "+872",
		"+48(PL)": "+48",
		"+351(PT)": "+351",
		"+1939(PR)": "+1939",
		"+974(QA)": "+974",
		"+40(RO)": "+40",
		"+7(RU)": "+7",
		"+250(RW)": "+250",
		"+262(RE)": "+262",
		"+590(BL)": "+590",
		"+290(SH)": "+290",
		"+1869(KN)": "+1869",
		"+1758(LC)": "+1758",
		"+590(MF)": "+590",
		"+508(PM)": "+508",
		"+1784(VC)": "+1784",
		"+685(WS)": "+685",
		"+378(SM)": "+378",
		"+239(ST)": "+239",
		"+966(SA)": "+966",
		"+221(SN)": "+221",
		"+381(RS)": "+381",
		"+248(SC)": "+248",
		"+232(SL)": "+232",
		"+65(SG)": "+65",
		"+421(SK)": "+421",
		"+386(SI)": "+386",
		"+677(SB)": "+677",
		"+252(SO)": "+252",
		"+27(ZA)": "+27",
		"+211(SS)": "+211",
		"+500(GS)": "+500",
		"+34(ES)": "+34",
		"+94(LK)": "+94",
		"+249(SD)": "+249",
		"+597(SR)": "+597",
		"+47(SJ)": "+47",
		"+268(SZ)": "+268",
		"+46(SE)": "+46",
		"+41(CH)": "+41",
		"+963(SY)": "+963",
		"+886(TW)": "+886",
		"+992(TJ)": "+992",
		"+255(TZ)": "+255",
		"+66(TH)": "+66",
		"+670(TL)": "+670",
		"+228(TG)": "+228",
		"+690(TK)": "+690",
		"+676(TO)": "+676",
		"+1868(TT)": "+1868",
		"+216(TN)": "+216",
		"+90(TR)": "+90",
		"+993(TM)": "+993",
		"+1649(TC)": "+1649",
		"+688(TV)": "+688",
		"+256(UG)": "+256",
		"+380(UA)": "+380",
		"+971(AE)": "+971",
		"+44(GB)": "+44",
		"+1(US)": "+1",
		"+598(UY)": "+598",
		"+998(UZ)": "+998",
		"+678(VU)": "+678",
		"+58(VE)": "+58",
		"+84(VN)": "+84",
		"+1284(VG)": "+1284",
		"+1340(VI)": "+1340",
		"+681(WF)": "+681",
		"+967(YE)": "+967",
		"+260(ZM)": "+260",
		"+263(ZW)": "+263"
		}.sort_by { |k| k[1].split('+')[1].to_i }.to_h
	end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/web/users_helper.rb
module Web::UsersHelper

	def category
		Category.all
	end

	def trending
		Product.where(trending: true)
	end

	def user_name id
		User.find_by(id: id)&.name
	end

	def user_image id
		User.find_by(id: id)&.image
	end

	def meta_review(product)
		status = false
			product.reviews.each do |review|
				status = true if User.find_by(id: review&.user_id)&.user_type == "Expert User"
				break if status
			end
		status
	end

	def review_vote_status(id)
		review = Review.find_by(id: id)
		# this_vote = review&.votes.where(user_id: current_user.id)&.first
		this_vote = review&.votes&.first#.where(user_id: current_user.id)&.first
        
		if this_vote.present?
			return this_vote&.vote_status
		else
			return false
		end

	end

	def review_vote_status_dislike(id)
		review = Review.find_by(id: id)
		# this_vote = review&.votes.where(user_id: current_user.id)&.first
		this_vote = review&.votes&.first#.where(user_id: current_user.id)&.first
        
		if this_vote.present?
			return this_vote&.vote_status
		else
			return true
		end

	end

	def voting_like_count(review)
		Review.find_by(id: review).votes.where(vote_status: true).count rescue 0
		# review.votes.where(vote_status: true).count
	end

	def voting_dislike_count(review)
		Review.find_by(id: review).votes.where(vote_status: false).count rescue 0
		# review.votes.where(vote_status: false).count
	end

	def get_poster url
		url.sub(/\.[^.]+\z/, '.png') if url.present?
	end

end

app/views/admin/users/admin_profile.html.erb
<section class="content-header">
  <center>
    <h1><b>Admin Profile</b></h1>
      <p class="box box-info"></p>
   </center>
</section>
<section class="content">
  <div class="row">
     <div class="col-md-3">

     </div>
     <div class="col-md-6">
   <!-- <h3>User Detail</h3> -->
      <div class="box box">
       <%= link_to '<em class="fa fa-edit" aria-hidden="true"></em>'.html_safe, edit_admin_profile_admin_user_path(current_user), class:"btn btn-sm btn-primary pull-right" ,title: "Edit" %>
         <div class="box-body box-profile">
            <center> <img src='<%= current_user&.image&.file&.present? ? current_user&.image&.file&.try(:url) : "/assets/user_default.jpeg" %>' class="img-circle" alt="Image Not Found" id="user_pic"  onchange = "preview(this)" height=200px width=200px /><i style="position: absolute; margin-top: 47px; margin-left: -45px; font-size: 24px;" ></i>
                 </center><br>

           <p class="box box-info"></p>
           <h3 class="profile-username text-center">
               <%#= @user.name.capitalize %>
           </h3>
           <p class="text-muted text-center">
                 <%#= @user.role.capitalize %>
           </p>
           <ul class="list-group list-group-unbordered">
               <li class="list-group-item">
                  <b>Name</b>
                     <p class="pull-right">
                       <%= @user&.name&.capitalize%>
                     </p>
               </li>
               <li class="list-group-item">
                   <b>Email Id</b>
                   <p class="pull-right">
                   <%= @user&.email%>
                   </p>
               </li>
               <li class="list-group-item">
                    <b>Role</b>
                     <p class="pull-right">
                       <%= @user&.role%>
                     </p>
               </li>
               
               <li class="list-group-item">
                   <b>Mobile No.</b>
                   <p class="pull-right">
                   <%= @user&.mobile_no%>
                      <%#= @transaction&.created_at.strftime("%d/%m/%Y")%>
                   </p>
               </li>
            </ul>
          <a href="/admin/users" class="btn btn-danger btn-block"><b>Back</b></a>
        </div>
       <!-- /.box-body -->
      </div>
   </div>
  <div class="col-md-3">
  </div>
 </div>
</section>

                    

app/views/admin/users/change_admin_password.html.erb
<h1>Hello Users</h1>

app/views/admin/users/index.html.erb
<h1>User Management</h1>
<div class="box box-info">
<%#= form_tag import_admin_users_path, multipart: true, id: "controls-form", class: "shubham" do %>
             <%#= file_field_tag :file, id: "fileinput", accept: ".csv" %>
             <%#= submit_tag "Import" %>
              <%# end %>

<%= form_with scope: :search, url: admin_users_path, method: :get,autocomplete: :off,local: true do |f| %>
    <div class="box-header">
      <div class="form-group"> 
       <label>Search by Email or Name:</label>
           <%= f.text_field :search, class: "form-control", placeholder:"Search",value: (params.dig :search, :search), :autocomplete => :off %>
        </div>
        <!-- <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
            </div> -->
    </div>
    <!-- /.box-header -->
    
    <div class="box-body">
        <div class="row">
            <!-- /.col -->
           
            <!-- /.col -->
            <div class="col-md-2">
                <!-- /.form-group -->
                <div class="form-group">
                    <label>Select status:</label>
                    <%= f.select(:status, options_for_select(["Normal User" ,"Expert User"],(params.dig :search, :search)) , {:include_blank => "Select User Type"}, {:class => "form-control"} ) %>
                </div>
            </div>
            <!-- /.form-group -->
            <div class="col-md-2">
                <!-- /.form-group -->
                <div class="form-group">
                    <label>From date:</label>
                    <div class="input-group date">
                        <div class="input-group-addon">
                            <em class="fa fa-calendar"></em>
                        </div>
                       <%= f.text_field :start,class: "form-control datetimepicker_start",placeholder:"Select Date",value: (params.dig :search, :start), autocomplete: :off,data: { provide: 'datepicker'} %>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <!-- /.form-group -->
                <div class="form-group">
                    <label>To date:</label>
                    <div class="input-group date">
                        <div class="input-group-addon">
                            <em class="fa fa-calendar"></em>
                        </div>
                       <%= f.text_field :end,class: "form-control datetimepicker_end",placeholder:"Select Date",value: (params.dig :search, :end),data:{provide: 'datepicker'}, :autocomplete => :off %>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <!-- /.form-group -->
                <div class="col-md-6">
                    <div class="form-group">
                        <label>&nbsp;</label>
                        <%= f.submit "Search", class: "btn btn-block btn-primary", title: "Search"%>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label>&nbsp;</label>
                        <%= link_to '<button class="btn btn-block btn-danger" type="button">Cancel</button>'.html_safe ,admin_users_path, title: "Cancel" %>
                    </div>
                </div>
                
                <!-- /.form-group -->
            </div>
              <%= link_to "CSV", admin_users_path(format: "csv"), class:"btn btn-success margin-top-25", title: "Download CSV"%> 
            

            <!-- /.col -->
            <!-- /.row -->
        </div>
    </div>
    <% end %>
    <!--Export CSV-->
    <%#= form_tag import_admin_users_path, multipart: true, id: "controls-form" do %>
    <%#= file_field_tag :file, id: "fileinput", accept: ".csv", class:"margin-top-60" %>
    <%#= submit_tag "Import", class:"btn btn-success margin-top-5" %>
    <%# end %>
    <!--Export CSV code finish-->

    <div class="box-body table-responsive ">
        <table class="table table-hover table-bordered">
            <tbody>
                <tr style="background-color: #D9D7D7;">
                    <th>Sr_No.</th>
                    <th>Name</th>
                    <th>User Type</th>
                    <th>Email-id</th>
                    <!-- <th>Phone No.</th> -->
                    <th>Registration date</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
                <br/>
                 <% if @search.blank? %>
                      <div class="global-heading user-head">No Record Found. </div>
                   <% else %>
                <% @users&.each do |user| %>
                <tr>
                    <td>
                        <%= @sr_no+=1 %>
                    </td>
                    <td>
                        <%= user&.name %>
                    </td>
                    <td>
                      <select >
                        <option><%= user&.user_type%></option>
                      </select>


                    </td>
                    <td>
                        <%= user&.email %>
                    </td>
                    <!-- <td>
                        <%#=user&.c_code%> <%#= user&.mobile_no %>
                    </td> -->
                    <td>
                        <%= user&.created_at %>
                    </td>
                    <td>
                        <%= user&.status_tag %>
                    </td>
                    <td>
                        <%= link_to '<em class="fa fa-eye" aria-hidden="true"></em>'.html_safe, admin_user_path(user), class:"btn btn-sm btn-success",title: "View"%>
                        <%= link_to '<em class="fa fa-edit" aria-hidden="true"></em>'.html_safe, edit_admin_user_path(user), class:"btn btn-sm btn-primary" ,title: "Edit" %>
                        
                        <%= user.block_btn %>
                        <%# if user&.user_type == "" || user&.user_type == "Expert User"%>
                        <%#= link_to '<em class="fa fa-users" aria-hidden="true"></em>'.html_safe, type_user_admin_user_path(user), method: :patch, class: "btn btn-success", title: "Normal Users", data: {confirm: "Are you sure change the user type to Normal User"} %>
                        <%#else%>
                        <%#= link_to '<em class="fa fa-user" aria-hidden="true"></em>'.html_safe, expert_user_admin_user_path(user), method: :patch, class: "btn btn-warning", id: 'btnsubmit', title: "Expert Users", data: {confirm: "Are you sure chnage the User type to Expert User"} %>
                        <%#end%>
                    </td>
                </tr>
                <%end%>
                <%end%>
            </tbody>
        </table>
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <div class="digg_pagination pull-right">
                <%= will_paginate @search %>
        </div>
    </div>
</div>
<style type="text/css">
   .margin-top-25 {
    margin-top: 25px;
    }
    .margin-top-60{
    margin-top: -60px;
    margin-left: 1050px;
    }
    .margin-top-5{
        margin-left: 1060px;
        margin-top: 5px;
    }
</style>

<!--js CSV file validation-->

<script type="text/javascript">
 $(function()
{
  $('#btnsubmit').on('click',function()
  {
    $(this).val('Please wait ...')
      .attr('disabled','disabled');
    $('#theform').submit();
  });
  
});

</script>

<!--js csv validation-->
<style type="text/css">
    input,
button,
select,
textarea {
  width: 100px;
}
</style>