config/routes.rb
Rails.application.routes.draw do
  get '/auth/facebook/callback' , to: 'users/sessions#create_user'

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    get 'homes/index'
  end
  #devise_for :users
     devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        omniauth_callbacks: "users/omniauth_callbacks" 
        #registrations: 'users/registrations'
      }


  namespace :web do
    resources :categories do
    collection do
      get :review_system
    end
    end

    resources :reviews do
      collection do
        get :review_chart, to: 'reviews#review_chart', as: 'review_chart'
        post :average_criteria
        post :average_bar_graph_data
        post :get_reviews
        post :get_vote_for_review
      end
    end
    get '/:name' , to: 'users#index' , as: 'users'
    resources :users, except: [:index] do
    collection do
      get :read_full_review
      get :check_email
      get :check_email_login
      post :image_update
      get :report
      get :report_details
      get :header_search
      get :user_score
      get :rating_product
      get :hollframe
      get :user_type
      get :trending
      get :upcomeing
      get :holl_of_fame_details
      get :categorywise
      get :rating_calculate
    end
    member do
      get :blockchain_data
      get :user_profile
      get :movie_category
      get :movie_category_detail
      get :movie_detail
      get :movie_review
      get :full_review
    end
   end 
  end

  namespace :admin do
    resources :users do
      collection do
        post :import
        get :change_admin_password
        # get :feedback
      end
    member do
        get :status
        get :admin_profile
        get :edit_admin_profile
        patch :update_admin_profile
        patch :type_user
        patch :expert_user
        # get :show_feedback
        # delete :destroy_feedback
      end
    end
    resources :faqs
    resources :feedbacks
    resources :static_content
    resources :categories do
      collection do
        get :edit_sub_category
        get :edit_review_part
       delete :destroy_sub_category
       delete :destroy_review_part
        post :create_sub_category
        post :create_post_review
        post :update_sub_category
        post :update_review_part
        get :add_category
        post :create_category_details
        get :search_sub_categories
      end
    end
    resources :products do
      collection do
        get :sub_categories_by_category
      end
      member do 
        patch :publish
        patch :show_in_banner
        get :add_links
        get :new_addlinks
        post :create_product_link
        delete :product_link_delete
        patch :unpublish
        patch :trending
      end
    end
      get 'homes/index', as: "home_index"
  end
   resources :homes do
      collection do
        get :about_us
        get :faq
        get :privacy_policy
        get :term_condition
        get :feedback
        get :contact_us
      end
    end
    root :to =>  "web/users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :users do
        collection do
            post :sign_up
            
        end 
      end
    end
  end

end

app/views/layouts/_admin_lte_2_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="/" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>L</b>OI</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Lina Review</b></span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="javascript:void(0)" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->
        <li class="dropdown messages-menu">
          <!-- Menu toggle button -->
          <!-- <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"> -->
            <!-- <i class="fa fa-envelope-o"></i> -->
            <!-- <span class="label label-success">4</span> -->
          <!-- </a> -->
          <ul class="dropdown-menu">
            <li class="header">You have 4 messages</li>
            <li>
              <!-- inner menu: contains the messages -->
              <ul class="menu">
                <li><!-- start message -->
                  <a href="javascript:void(0)">
                    <div class="pull-left">
                      <!-- User Image -->
                      <img src="/assets/user2-160x160.jpg" class="img-circle" alt="User Image"/>
                    </div>
                    <!-- Message title and timestamp -->
                    <h4>
                      Support Team
                      <small><i class="fa fa-clock-o"></i> 5 mins</small>
                    </h4>
                    <!-- The message -->
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li><!-- end message -->
              </ul><!-- /.menu -->
            </li>
            <li class="footer"><a href="javascript:void(0)">See All Messages</a></li>
          </ul>
        </li><!-- /.messages-menu -->

        <!-- Notifications Menu -->
        <li class="dropdown notifications-menu">
          <!-- Menu toggle button -->
          <!-- <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"> -->
            <!-- <i class="fa fa-bell-o"></i> -->
            <!-- <span class="label label-warning">10</span> -->
          <!-- </a> -->
          <ul class="dropdown-menu">
            <li class="header">You have 10 notifications</li>
            <li>
              <!-- Inner Menu: contains the notifications -->
              <ul class="menu">
                <li><!-- start notification -->
                  <a href="javascript:void(0)">
                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                  </a>
                </li><!-- end notification -->
              </ul>
            </li>
            <li class="footer"><a href="javascript:void(0)">View all</a></li>
          </ul>
        </li>
        <!-- Tasks Menu -->
        <li class="dropdown tasks-menu">
          <!-- Menu Toggle Button -->
          <!-- <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"> -->
            <!-- <i class="fa fa-flag-o"></i> -->
            <!-- <span class="label label-danger">9</span> -->
          <!-- </a> -->
          <ul class="dropdown-menu">
            <li class="header">You have 9 tasks</li>
            <li>
              <!-- Inner menu: contains the tasks -->
              <ul class="menu">
                <li><!-- Task item -->
                  <a href="javascript:void(0)">
                    <!-- Task title and progress text -->
                    <h3>
                      Design some buttons
                      <small class="pull-right">20%</small>
                    </h3>
                    <!-- The progress bar -->
                    <div class="progress xs">
                      <!-- Change the css width attribute to simulate progress -->
                      <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">20% Complete</span>
                      </div>
                    </div>
                  </a>
                </li><!-- end task item -->
              </ul>
            </li>
            <li class="footer">
              <a href="javascript:void(0)">View all tasks</a>
            </li>
          </ul>
        </li>
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <img src='<%= current_user&.image&.file&.present? ? current_user&.image&.file&.try(:url) : "/assets/user_default.jpeg" %>' class="img-circle" alt="Image Not Found"  height=20px width=20px /><i style="position: absolute; margin-top: 47px; margin-left: -45px; font-size: 24px;" ></i>
<!--             <img src="/assets/user2-160x160.jpg" class="user-image" alt="User Image"/>
 -->            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs"><%= current_user&.name %></span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <img src='<%= current_user&.image&.file&.present? ? current_user&.image&.file&.try(:url) : "/assets/user_default.jpeg" %>' class="img-circle" alt="Image Not Found"  height=200px width=200px /><i style="position: absolute; margin-top: 47px; margin-left: -45px; font-size: 24px;" ></i>
              <!-- <img src="/assets/user2-160x160.jpg" class="img-circle" alt="User Image" /> -->
              <p>
                <%= current_user&.name %>
                <!-- <small>Member since Nov. 2012</small> -->
              </p>
            </li>
            <!-- Menu Body -->
         <!--    <li class="user-body">
              <div class="col-xs-4 text-center">
                <a href="javascript:void(0)">Followers</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="javascript:void(0)">Sales</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="javascript:void(0)">Friends</a>
              </div>
            </li> -->
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="/admin/users/<%= current_user&.id%>/admin_profile" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <!-- <a href="/users/sign_out" class="btn btn-default btn-flat">Sign out</a> -->
                 <%= link_to "Sign out", destroy_user_session_path, :class=> "btn btn-default btn-flat"  %>
              </div>
            </li>
          </ul>
        </li>
       <!--  <li>
          <a href="javascript:void(0)" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li> -->
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_admin_lte_2_sidebar.html.erb
 <!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src='<%= current_user&.image&.file&.present? ? current_user&.image&.file&.try(:url) : "/assets/user_default.jpeg" %>' class="img-circle" alt="Image Not Found"  height=200px width=200px /><i style="position: absolute; margin-top: 47px; margin-left: -45px; font-size: 24px;" ></i>
        <!-- <img src="/assets/user2-160x160.jpg" class="img-circle" alt="User Image" /> -->
      </div>
      <div class="pull-left info">
        <p>Welcome <%= current_user&.name %></p>
        <p><%#= current_user&.email %></p>
        <!-- Status -->
        <!-- <a href="javascript:void(0)"><i class="fa fa-circle text-success"></i> Online</a> -->
      </div>
    </div>

    <!-- search form (Optional) -->
    <form action="javascript:void(0)" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search..."/>
        <span class="input-group-btn">
          <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
        </span>
      </div>
    </form>
    <!-- /.search form -->

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <!-- <li class="header">HEADER</li> -->
        <!-- Optionally, you can add icons to the links -->
      <li id="index"><a href="/admin/homes/index"><i class='fa fa-link'></i> <span>Dashboard</span></a></li>
      <li id="users"><a href="/admin/users"><i class="fa fa-users"></i> <span>User Management</span></a></li>
      <li id="categories"><a href="/admin/categories"><i class="fa fa-link"></i> <span>Category Management</span></a></li>
      <li id="products"><a href="/admin/products"><i class="fa fa-link"></i> <span>Products Management</span></a></li>
      <li id="static_content" ><a href="/admin/static_content"><i class='fa fa-link'></i> <span>Static Content Management</span></a></li>
            <li id="faqs" ><a href="/admin/faqs"><i class='fa fa-link'></i> <span>Faqs Management</span></a></li>
      <li id="feedbacks" ><a href="/admin/feedbacks"><i class='fa fa-user'></i> <span>User Feedback</span></a></li>

      <!-- <li><a href="javascript:void(0)"><i class='fa fa-link'></i> <span>Another Link</span></a></li> -->
     <!--  <li class="treeview">
        <a href="javascript:void(0)"><i class='fa fa-link'></i> <span>Multilevel</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><a href="javascript:void(0)">Link in level 2</a></li>
          <li><a href="javascript:void(0)">Link in level 2</a></li>
        </ul>
      </li> -->
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

<script type="text/javascript">
 // on click change active class js on home page.
$(function() {
 // debugger;
pathname = window.location.pathname;
url_array = location.pathname.split("/");
if (url_array.length <= 2)
 { 
 element = $("#"+url_array[1])[0];
 element.classList.add("active");
 }
 else if(url_array.length == 3)
 {
 element = $("#"+url_array[2])[0];
   element.classList.add("active");
 }
else if(url_array.length==4)
 {
   if (url_array[3]=="feedback" || url_array[3] == "index")
   {
     element = $("#"+url_array[3])[0];
    element.classList.add("active");
   }
   else
   {
   element = $("#"+url_array[2])[0];
   element.classList.add("active");
   }
 }
 else if(url_array.length == 5 && url_array[4]=="edit")
 {
  element = $("#"+url_array[2])[0];
  element.classList.add("active");
 }

else if(url_array.length<=4 && url_array[2] == "faqs")
 {
 element = $("#"+url_array[2])[0];
   element.classList.add("active");
 }
 
else
 {
    element = $("#"+url_array[4])[0];
    element.classList.add("active");
 }
});
// on click change active class js end on home page.
</script>
<style type="text/css">
 .skin-blue .sidebar-menu>li:hover>a, .skin-blue .sidebar-menu>li.active>a {
   color: #fff;
   background: #f39c12;
   border-left-color: #3c8dbc;
}
</style>

app/views/layouts/_alert.html.erb
<% if notice %>
<% notice.each do |noti| %>
<div class="alert alert-success alert-dismissable">
    <i class="fa fa-check"></i>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <b>&nbsp;
        <%= noti %></b>
</div>
<% end %>
<% end %>
<% if alert %>
<% alert.each do |err| %>
<div class="alert alert-danger alert-dismissable">
    <i class="fa fa-ban"></i>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <b>&nbsp;
        <%= err %></b>
</div>
<% end %>
<% end %>
<% flash.clear %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
        <center><%= value.join%></center>
    </ul>
  </div>
<% end %>
<% flash.clear %>
<style type="text/css">
.alert-error {
  background-color: #e80b0b;
  border-color: #e80b0b;
  color: #fbf9f9;
  z-index: 99 !important; 
  position:absolute;
  top: 105px;
  width: 1108px;
  height: 50px;
  margin: auto;
    left: 50%;
    transform: translateX(-50%);
 }

.alert-alert {
  background-color: #e80b0b;
  border-color: #e80b0b;
  color: #fbf9f9;
  z-index: 99 !important; 
  position:absolute;
  top: 105px;
  width: 1108px;
  height: 50px;
  margin: auto;
    left: 50%;
    transform: translateX(-50%);
 }

.alert-success {
  background-color: #048e0f;
  border-color: #048e0f;
  color: #fbf9f9;
  z-index: 99 !important; 
  position:absolute;
  top: 105px;
  width: 1108px;
  height: 50px;
  margin: auto;
    left: 50%;
    transform: translateX(-50%);
 }

.alert-notice {
  background-color: #048e0f;
  border-color: #048e0f;
  color: #fbf9f9;
  z-index: 99 !important; 
  position:absolute;
  top: 105px;
  width: 1108px;
  height: 50px;
  margin: auto;
    left: 50%;
    transform: translateX(-50%);
 }
</style>
<script type="text/javascript">
	$(".alert" ).fadeOut(5000);
</script>

app/views/layouts/_web_footer.html.erb
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4 text-center">
                <div class="footer-widget footer-about">
                    <a href="<%= root_path%>"><img src="/assets/Lina1.png"></a>
                    <p class="fotter-para">The review platform based on blockchain technology, data will be guaranteed immutability and transparency. A product of Lina Network.</p>
                </div>
            </div>
            <div class="col-md-5">
                <div class="row align-items-intial">
                    <div class="col-md-6">
                        <div class="footer-widget footer-menu">
                            <ul class="fotter-ul">
                                <li class="main-hedaing">Support</li>
                                <li><a href="/homes/about_us">About Us</a></li>
                                <li><a href="/homes/contact_us">Contact Us</a></li>
                                <li><a href="/homes/feedback">Give Us Feedback</a></li>
                                <li><a href="/homes/faq">FAQs</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="footer-widget footer-menu">
                            <ul class="fotter-ul">
                                <li class="main-hedaing">More Information</li>
                                <li><a href="/homes/term_condition">Terms & Conditions</a></li>
                                <li><a href="/homes/privacy_policy">Privacy Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="footer-widget footer-social">
                    <a href="https://www.facebook.com/pg/linareviewvn" class="font-awsomeicon"><i class="fa fa-facebook"></i></a>
                    <a href="https://medium.com/@lina.network" class="font-awsomeicon"><i class="fa fa fa-medium"></i></a>
                    <a href=" https://www.youtube.com/channel/UCswoAu7ENbSQ01ruLhurEoQ" class="font-awsomeicon"><i class="fa fa fa-youtube"></i></a>
                    <a href="https://twitter.com/lina_network?lang=en" class="font-awsomeicon"><i class="fa fa-twitter"></i></a>
                    <a href="https://web.telegram.org/#/im?p=@LinaNews" class="font-awsomeicon"><i class="fa fa-telegram"></i></a>

                </div>
            </div>
        </div>
    </div>
    <div class="last-para copyright text-center">
        <div class="container">
            <p class="mb-0">All rights are reserved @ Lina.network <%= Time.now.year%></p>
        </div>
    </div>
</footer>

<style type="text/css">
    a.font-awsomeicon i.fa {
        height: 36px;
        width: 36px;
        line-height: 36px;
    }
    .footer-about{
        text-align:left;
    }
    .footer-about img{
        max-width:100px;
    }
</style>

app/views/layouts/_web_header.html.erb
<header id="header" class="header">
    <nav id="main-navbar" class="main-navbar navbar navbar-expand-lg bg-primary">
        <div class="headerTop">
            <!-- <a class="navbar-brand" href="<%= root_path%>"><img src="/assets/LOGO.png"></a> -->
            <a class="navbar-brand" href="<%= root_path%>"><img src="/assets/Lina1.png"></a>

            <ul class="navbar-nav align-items-center">
                <li class="nav-item">
                      <!-- <form class="header-search"> -->
            <%=form_tag "/web/users/header_search", method: :get,  class:"header-search" do  %>                     
                    <input type="search" name="search" class="form-control" placeholder="Search Product">
                        <img src="/assets/search.png">
                    <%end%>
                    <!-- </form> -->
                </li>
            </ul>
            <ul class="navbar-nav align-items-center">
                <%if current_user%>
                <li class="nav-item user-item"><a class="" href="/web/users/<%= current_user.id %>/user_profile"><span>
                            <%= current_user&.name%></span> <img src="<%= current_user&.image&.file&.present? ? current_user&.image&.file&.try(:url) : "/assets/user_default.jpeg" %>" alt=""> </a></li>
                <li><a class="nav-link btn btn-theme" href="#" data-toggle="modal" data-target="#logoutModal">Log Out</a>
               
                </li>
                <%else%>
                <li>
                    <%= link_to "+ Join Us", new_user_registration_path, :class => 'nav-link btn btn-theme mr-3'  %>
                </li>
                <li>
                    <%= link_to "Login", new_user_session_path, :class => 'nav-link btn btn-theme'  %>
                </li>
                <%end%>
            </ul>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav align-items-center main-nav">
                <%if @product.present?%>
                <%xyz = @product&.category&.id%>
                <%else%>
                <%xyz = @sub_category&.category&.id%>
                <%end%>
                <% category.each do |category|%>
                <li class="nav-item dropdown mega-dropdown">
             
<a class="nav-link user_type dropdown-toggle shubham <%= xyz == category.id ? "active" : "" %>" aria-haspopup="true" aria-expanded="false" href="<%= web_users_path(category.category_name)%>" id="<%= category.id%>"><%= category.category_name%></a>
                    <div class="dropdown-menu mega-menu">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="custom-post m-0">
                                    <div class="custom-img">
                                        <% arr = category.sub_categories.includes(:products).map{ |s_c| s_c.products.map { |p| p&.image&.first&.file&.url}}.flatten.compact%>
                                        <%if arr.present? %>
                                        <img src="<%=arr[0]%>" class="img-fluid" alt="">
                                        <%else%>
                                        <img src="/assets/mega-drop-img.jpg" class="img-fluid" alt="">
                                        <%end%>
                                    </div>
                                    <div class="custom-content justify-content-end">
                                        <p class="mb-2" >
                                            <%= category.category_name %>
                                        </p>
                                    
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="row">
                                    <% category&.sub_categories.each_with_index do |sub, index| %>
                                    <% if index <= 2 && index %>
                                    <div class="col-md-3">
                                        <ul class="mega-menu-list">
                                            <li>
                                                
                                                <a class="" role="button" href="/web/users/<%=sub.id%>/movie_category">
                                                    <%= sub&.sub_category_name%></a>
                                            </li>
                        
                                        </ul>
                                    </div>
                                    <% elsif index <= 5%>
                                    <div class="col-md-3">
                                        <ul class="mega-menu-list">
                                            <li>
                                                <a href="/web/users/<%=sub.id%>/movie_category" class="custom-post">
                                              
                                                    <%= sub&.sub_category_name%></a></li>
                                        </ul>
                                    </div>
                                    <%elsif index <= 30%>
                                    <div class="col-md-3">
                                        <ul class="mega-menu-list">
                                            <li><a href="/web/users/<%=sub.id%>/movie_category">
                                                    <%= sub&.sub_category_name%></a></li>
                                        </ul>
                                    </div>
                                    <%end%>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <%end%>
                <li class="nav-item dropdown mega-dropdown">
                    <% if params[:action] == "report"%>
                    <a class="nav-link shubham active" href="/web/users/report">Reports</a>
                    <%else%>
                    <a class="nav-link shubham" href="/web/users/report">Reports</a>
                    <%end%>
                </li>
            </ul>
        </div>
    </nav>
</header>
<div class="modal logoutModal" id="logoutModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content text-center">
            <div class="modal-header">
                <h5 class="modal-title">LOGOUT</h5>
                
            </div>
            <div class="modal-body">
                <p class="mt-4 bigtitle">Are you sure you want to Logout?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-light" data-dismiss="modal">No</button>
                <div class="profil-btn">
                    <%= link_to "Yes", destroy_user_session_path, class: "btn btn-theme" %>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

</script>
<style type="text/css">
    .shubham:hover{
        color: #fe7100;
        font-weight: bold;
    }

</style>
<!-- <script type="text/javascript">

$(document).ready(function(){
      $('#1').click();
      $('.change_data').click(function(){

        var id=$(this).attr("id");
      $.ajax({
         url: '/web/users.js?only=page',
         type: 'get',
         data: {
          id: id
          },
          success: function(data){
            debugger;
             var a = $(data);
           
      }
       });
    });
 });
</script> -->

<style type="text/css">
    .navbar-brand{
        max-width:70px;
    }
     .navbar-brand img{
        max-width:120px;
    }
    .main-nav>li>a {
    padding: 14px 8px!important;
    text-align: center;
    color: #fff;
    font-family: poppins,sans-serif;
    position: relative;
    word-break: normal;
}
</style>

app/views/layouts/admin_lte_2_login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>AdminLTE 2 | Log in</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag 'admin/admin_application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>Admin</b>LTE</a>
  </div><!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="form-group has-feedback">
        <%= f.text_field :email, class: 'form-control', autofocus: true %>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>

      <div class="form-group has-feedback">
        <%= f.password_field :password, class: 'form-control', autocomplete: 'off' %>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
        </div><!-- /.col -->
        <div class="col-xs-4">
          <%= f.submit 'Log in', class: 'btn btn-primary btn-block btn-flat' %>

        </div><!-- /.col -->
      </div>

    <% end %>
  </div><!-- /.login-box-body -->
</div><!-- /.login-box -->

<%= javascript_include_tag 'admin/admin_application', 'data-turbolinks-track' => true %>
</body>
</html>